#!/bin/bash
check_installed=`cat ~/.bashrc | grep JAVAMARKUP_HOME`

echo -e "\033[1mSetting up environment\033[0m";

if [ -n "${check_installed}" ]; then
	sed -i.bak "/export JAVAMARKUP_HOME=/d" ~/.bashrc
fi
javamarkup_home=`pwd`
echo "" >> ~/.bashrc
export JAVAMARKUP_HOME=${javamarkup_home}
echo "export JAVAMARKUP_HOME=${javamarkup_home}" >> ~/.bashrc

OUTPUT="bin"
if [ -d "$OUTPUT" ]; then
	echo "Using already existing bin/ folder";
else 
	mkdir bin
fi

echo -e "\033[1mCompiling Source code\033[0m";

echo -e "\033[1mCompiling\033[0m ${JAVAMARKUP_HOME}/src/javamarkup/utilities/Sys.java";
javac -d ${JAVAMARKUP_HOME}/bin -sourcepath ${JAVAMARKUP_HOME}/src ${JAVAMARKUP_HOME}/src/javamarkup/utilities/Sys.java
echo -e "\033[1mCompiling\033[0m ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/CommentRemover.java";
javac -d ${JAVAMARKUP_HOME}/bin -sourcepath ${JAVAMARKUP_HOME}/src ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/CommentRemover.java
echo -e "\033[1mCompiling\033[0m ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/Type.java";
javac -d ${JAVAMARKUP_HOME}/bin -sourcepath ${JAVAMARKUP_HOME}/src ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/Type.java
echo -e "\033[1mCompiling\033[0m ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/State.java";
javac -d ${JAVAMARKUP_HOME}/bin -sourcepath ${JAVAMARKUP_HOME}/src ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/State.java
echo -e "\033[1mCompiling\033[0m ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/TransitionDiagram.java";
javac -d ${JAVAMARKUP_HOME}/bin -sourcepath ${JAVAMARKUP_HOME}/src ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/TransitionDiagram.java
echo -e "\033[1mCompiling\033[0m ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/SymbolRecord.java";
javac -d ${JAVAMARKUP_HOME}/bin -sourcepath ${JAVAMARKUP_HOME}/src ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/SymbolRecord.java
echo -e "\033[1mCompiling\033[0m ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/Tokenizer.java";
javac -d ${JAVAMARKUP_HOME}/bin -sourcepath ${JAVAMARKUP_HOME}/src ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/Tokenizer.java
echo -e "\033[1mCompiling\033[0m ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/LexicalAnalyser.java";
javac -d ${JAVAMARKUP_HOME}/bin -sourcepath ${JAVAMARKUP_HOME}/src ${JAVAMARKUP_HOME}/src/javamarkup/lexicalanalyser/LexicalAnalyser.java
echo -e "\033[1mCompiling\033[0m ${JAVAMARKUP_HOME}/src/javamarkup/Main.java";
javac -d ${JAVAMARKUP_HOME}/bin -sourcepath ${JAVAMARKUP_HOME}/src ${JAVAMARKUP_HOME}/src/javamarkup/Main.java

echo -e "\033[1mFinishing installation\033[0m";
echo "java -classpath ${JAVAMARKUP_HOME}/bin javamarkup.Main \$@" > ~/jmparse
sudo mv ~/jmparse /usr/local/bin/jmparse
sudo chmod +x /usr/local/bin/jmparse

echo "";
echo -e "\033[1;32mJavaMarkup installation complete!!\033[0m";