package javamarkup.semanticanalyser;

public class Mapper {
	public static Tag getTagObj(String tagname){
		switch(tagname){
			case "a"	:	return new A();
			case "abbr"	:	return new Abbr();
			case "acronym"	:	return new Acronym();
			case "address"	:	return new Address();
			case "applet"	:	return new Applet();
			case "area"	:	return new Area();
			case "article"	:	return new Article();
			case "aside"	:	return new Aside();
			case "audio"	:	return new Audio();
			case "b"	:	return new B();
			case "base"	:	return new Base();
			case "basefont"	:	return new Basefont();
			case "bdi"	:	return new Bdi();
			case "bdo"	:	return new Bdo();
			case "big"	:	return new Big();
			case "blockquote"	:	return new Blockquote();
			case "body"	:	return new Body();
			case "br"	:	return new Br();
			case "button"	:	return new Button();
			case "canvas"	:	return new Canvas();
			case "caption"	:	return new Caption();
			case "center"	:	return new Center();
			case "cite"	:	return new Cite();
			case "code"	:	return new Code();
			case "col"	:	return new Col();
			case "colgroup"	:	return new Colgroup();
			case "datalist"	:	return new Datalist();
			case "dd"	:	return new Dd();
			case "del"	:	return new Del();
			case "details"	:	return new Details();
			case "dfn"	:	return new Dfn();
			case "dialog"	:	return new Dialog();
			case "dir"	:	return new Dir();
			case "div"	:	return new Div();
			case "dl"	:	return new Dl();
			case "dt"	:	return new Dt();
			case "em"	:	return new Em();
			case "embed"	:	return new Embed();
			case "fieldset"	:	return new Fieldset();
			case "figcaption"	:	return new Figcaption();
			case "figure"	:	return new Figure();
			case "font"	:	return new Font();
			case "footer"	:	return new Footer();
			case "form"	:	return new Form();
			case "frame"	:	return new Frame();
			case "frameset"	:	return new Frameset();
			case "h1"	:	return new H1();
			case "h2"	:	return new H2();
			case "h3"	:	return new H3();
			case "h4"	:	return new H4();
			case "h5"	:	return new H5();
			case "h6"	:	return new H6();
			case "head"	:	return new Head();
			case "header"	:	return new Header();
			case "hr"	:	return new Hr();
			case "html"	:	return new Html();
			case "i"	:	return new I();
			case "iframe"	:	return new Iframe();
			case "img"	:	return new Img();
			case "input"	:	return new Input();
			case "ins"	:	return new Ins();
			case "kbd"	:	return new Kbd();
			case "keygen"	:	return new Keygen();
			case "label"	:	return new Label();
			case "legend"	:	return new Legend();
			case "li"	:	return new Li();
			case "link"	:	return new Link();
			case "main"	:	return new Main();
			case "map"	:	return new Map();
			case "mark"	:	return new Mark();
			case "menu"	:	return new Menu();
			case "menuitem"	:	return new Menuitem();
			case "meta"	:	return new Meta();
			case "meter"	:	return new Meter();
			case "nav"	:	return new Nav();
			case "noframes"	:	return new Noframes();
			case "noscript"	:	return new Noscript();
			case "object"	:	return new Object();
			case "ol"	:	return new Ol();
			case "optgroup"	:	return new Optgroup();
			case "option"	:	return new Option();
			case "output"	:	return new Output();
			case "p"	:	return new P();
			case "param"	:	return new Param();
			case "picture"	:	return new Picture();
			case "pre"	:	return new Pre();
			case "progress"	:	return new Progress();
			case "q"	:	return new Q();
			case "rp"	:	return new Rp();
			case "rt"	:	return new Rt();
			case "ruby"	:	return new Ruby();
			case "s"	:	return new S();
			case "samp"	:	return new Samp();
			case "script"	:	return new Script();
			case "section"	:	return new Section();
			case "select"	:	return new Select();
			case "small"	:	return new Small();
			case "source"	:	return new Source();
			case "span"	:	return new Span();
			case "strike"	:	return new Strike();
			case "strong"	:	return new Strong();
			case "style"	:	return new Style();
			case "sub"	:	return new Sub();
			case "summary"	:	return new Summary();
			case "sup"	:	return new Sup();
			case "table"	:	return new Table();
			case "tbody"	:	return new Tbody();
			case "td"	:	return new Td();
			case "tfoot"	:	return new Tfoot();
			case "th"	:	return new Th();
			case "thead"	:	return new Thead();
			case "time"	:	return new Time();
			case "title"	:	return new Title();
			case "tr"	:	return new Tr();
			case "track"	:	return new Track();
			case "tt"	:	return new Tt();
			case "u"	:	return new U();
			case "ul"	:	return new Ul();
			case "var"	:	return new Var();
			case "video"	:	return new Video();
			case "wbr"	:	return new Wbr();
			default : return null;
		}
	}

	public static String getMethod(Tag tag, String attr){
		switch(attr){
			case "accept" : return tag.getAccept();
			case "acceptCharset" : return tag.getAcceptCharset();
			case "action" : return tag.getAction();
			case "align" : return tag.getAlign();
			case "alt" : return tag.getAlt();
			case "async" : return tag.getAsync();
			case "autocomplete" : return tag.getAutocomplete();
			case "autofocus" : return tag.getAutofocus();
			case "autoplay" : return tag.getAutoplay();
			case "bgcolor" : return tag.getBgcolor();
			case "border" : return tag.getBorder();
			case "challenge" : return tag.getChallenge();
			case "charset" : return tag.getCharset();
			case "checked" : return tag.getChecked();
			case "cite" : return tag.getCite();
			case "color" : return tag.getColor();
			case "cols" : return tag.getCols();
			case "colspan" : return tag.getColspan();
			case "content" : return tag.getContent();
			case "controls" : return tag.getControls();
			case "coords" : return tag.getCoords();
			case "datetime" : return tag.getDatetime();
			case "default" : return tag.getDefault();
			case "defer" : return tag.getDefer();
			case "dirname" : return tag.getDirname();
			case "disabled" : return tag.getDisabled();
			case "download" : return tag.getDownload();
			case "enctype" : return tag.getEnctype();
			case "for" : return tag.getFor();
			case "form" : return tag.getForm();
			case "formaction" : return tag.getFormaction();
			case "headers" : return tag.getHeaders();
			case "height" : return tag.getHeight();
			case "high" : return tag.getHigh();
			case "href" : return tag.getHref();
			case "hreflang" : return tag.getHreflang();
			case "httpEquiv" : return tag.getHttpEquiv();
			case "ismap" : return tag.getIsmap();
			case "keytype" : return tag.getKeytype();
			case "kind" : return tag.getKind();
			case "label" : return tag.getLabel();
			case "list" : return tag.getList();
			case "loop" : return tag.getLoop();
			case "low" : return tag.getLow();
			case "manifest" : return tag.getManifest();
			case "max" : return tag.getMax();
			case "maxlength" : return tag.getMaxlength();
			case "media" : return tag.getMedia();
			case "method" : return tag.getMethod();
			case "min" : return tag.getMin();
			case "multiple" : return tag.getMultiple();
			case "muted" : return tag.getMuted();
			case "name" : return tag.getName();
			case "novalidate" : return tag.getNovalidate();
			case "open" : return tag.getOpen();
			case "optimum" : return tag.getOptimum();
			case "pattern" : return tag.getPattern();
			case "placeholder" : return tag.getPlaceholder();
			case "poster" : return tag.getPoster();
			case "preload" : return tag.getPreload();
			case "readonly" : return tag.getReadonly();
			case "rel" : return tag.getRel();
			case "required" : return tag.getRequired();
			case "reversed" : return tag.getReversed();
			case "rows" : return tag.getRows();
			case "rowspan" : return tag.getRowspan();
			case "sandbox" : return tag.getSandbox();
			case "scope" : return tag.getScope();
			case "scoped" : return tag.getScoped();
			case "selected" : return tag.getSelected();
			case "shape" : return tag.getShape();
			case "size" : return tag.getSize();
			case "sizes" : return tag.getSizes();
			case "span" : return tag.getSpan();
			case "src" : return tag.getSrc();
			case "srcdoc" : return tag.getSrcdoc();
			case "srclang" : return tag.getSrclang();
			case "srcset" : return tag.getSrcset();
			case "start" : return tag.getStart();
			case "step" : return tag.getStep();
			case "target" : return tag.getTarget();
			case "type" : return tag.getType();
			case "usemap" : return tag.getUsemap();
			case "value" : return tag.getValue();
			case "width" : return tag.getWidth();
			case "wrap" : return tag.getWrap();
			case "accesskey" : return tag.getAccesskey();
			case "contenteditable" : return tag.getContenteditable();
			case "contextmenu" : return tag.getContextmenu();
			case "dir" : return tag.getDir();
			case "data" : return tag.getData();
			case "draggable" : return tag.getDraggable();
			case "dropzone" : return tag.getDropzone();
			case "hidden" : return tag.getHidden();
			case "lang" : return tag.getLang();
			case "spellcheck" : return tag.getSpellcheck();
			case "style" : return tag.getStyle();
			case "tabindex" : return tag.getTabindex();
			case "title" : return tag.getTitle();
			case "translate" : return tag.getTranslate();
			case "onabort" : return tag.getOnabort();
			case "onafterprint" : return tag.getOnafterprint();
			case "onbeforeprint" : return tag.getOnbeforeprint();
			case "onbeforeunload" : return tag.getOnbeforeunload();
			case "onblur" : return tag.getOnblur();
			case "oncanplay" : return tag.getOncanplay();
			case "oncanplaythrough" : return tag.getOncanplaythrough();
			case "onchange" : return tag.getOnchange();
			case "onclick" : return tag.getOnclick();
			case "oncontextmenu" : return tag.getOncontextmenu();
			case "oncopy" : return tag.getOncopy();
			case "oncuechange" : return tag.getOncuechange();
			case "oncut" : return tag.getOncut();
			case "ondblclick" : return tag.getOndblclick();
			case "ondrag" : return tag.getOndrag();
			case "ondragend" : return tag.getOndragend();
			case "ondragenter" : return tag.getOndragenter();
			case "ondragleave" : return tag.getOndragleave();
			case "ondragover" : return tag.getOndragover();
			case "ondragstart" : return tag.getOndragstart();
			case "ondurationchanged" : return tag.getOndurationchanged();
			case "onemptied" : return tag.getOnemptied();
			case "onended" : return tag.getOnended();
			case "onerror" : return tag.getOnerror();
			case "onfocus" : return tag.getOnfocus();
			case "onhashchange" : return tag.getOnhashchange();
			case "oninput" : return tag.getOninput();
			case "oninvalid" : return tag.getOninvalid();
			case "onkeydown" : return tag.getOnkeydown();
			case "onkeypress" : return tag.getOnkeypress();
			case "onkeyup" : return tag.getOnkeyup();
			case "onload" : return tag.getOnload();
			case "onloaddeddata" : return tag.getOnloaddeddata();
			case "onloadedmetadata" : return tag.getOnloadedmetadata();
			case "onloadstart" : return tag.getOnloadstart();
			case "onmousedown" : return tag.getOnmousedown();
			case "onmousemove" : return tag.getOnmousemove();
			case "onmouseout" : return tag.getOnmouseout();
			case "onmouseover" : return tag.getOnmouseover();
			case "onmouseup" : return tag.getOnmouseup();
			case "onmousewheel" : return tag.getOnmousewheel();
			case "onoffline" : return tag.getOnoffline();
			case "ononline" : return tag.getOnonline();
			case "onpagehide" : return tag.getOnpagehide();
			case "onpageshow" : return tag.getOnpageshow();
			case "onpaste" : return tag.getOnpaste();
			case "onpuase" : return tag.getOnpuase();
			case "onplay" : return tag.getOnplay();
			case "onplaying" : return tag.getOnplaying();
			case "onpopstate" : return tag.getOnpopstate();
			case "onprogress" : return tag.getOnprogress();
			case "onratechange" : return tag.getOnratechange();
			case "onreset" : return tag.getOnreset();
			case "onresize" : return tag.getOnresize();
			case "onscroll" : return tag.getOnscroll();
			case "onsearch" : return tag.getOnsearch();
			case "onseeked" : return tag.getOnseeked();
			case "onseeking" : return tag.getOnseeking();
			case "onselect" : return tag.getOnselect();
			case "onshow" : return tag.getOnshow();
			case "onstalled" : return tag.getOnstalled();
			case "onstorage" : return tag.getOnstorage();
			case "onsubmit" : return tag.getOnsubmit();
			case "onsuspend" : return tag.getOnsuspend();
			case "ontimeupdate" : return tag.getOntimeupdate();
			case "ontoggle" : return tag.getOntoggle();
			case "onunload" : return tag.getOnunload();
			case "onvolumechange" : return tag.getOnvolumechange();
			case "onwaiting" : return tag.getOnwaiting();
			case "onwheel" : return tag.getOnwheel();
			case "class" : return tag.getClasses();
			case "id" : return tag.getId();
			default : return "";
		}
	}

	public static void setMethod(Tag tag, String attr, String value){
		switch(attr){
			case "accept" : tag.setAccept(value); break;
			case "acceptCharset" : tag.setAcceptCharset(value); break;
			case "action" : tag.setAction(value); break;
			case "align" : tag.setAlign(value); break;
			case "alt" : tag.setAlt(value); break;
			case "async" : tag.setAsync(value); break;
			case "autocomplete" : tag.setAutocomplete(value); break;
			case "autofocus" : tag.setAutofocus(value); break;
			case "autoplay" : tag.setAutoplay(value); break;
			case "bgcolor" : tag.setBgcolor(value); break;
			case "border" : tag.setBorder(value); break;
			case "challenge" : tag.setChallenge(value); break;
			case "charset" : tag.setCharset(value); break;
			case "checked" : tag.setChecked(value); break;
			case "cite" : tag.setCite(value); break;
			case "color" : tag.setColor(value); break;
			case "cols" : tag.setCols(value); break;
			case "colspan" : tag.setColspan(value); break;
			case "content" : tag.setContent(value); break;
			case "controls" : tag.setControls(value); break;
			case "coords" : tag.setCoords(value); break;
			case "datetime" : tag.setDatetime(value); break;
			case "default" : tag.setDefault(value); break;
			case "defer" : tag.setDefer(value); break;
			case "dirname" : tag.setDirname(value); break;
			case "disabled" : tag.setDisabled(value); break;
			case "download" : tag.setDownload(value); break;
			case "enctype" : tag.setEnctype(value); break;
			case "for" : tag.setFor(value); break;
			case "form" : tag.setForm(value); break;
			case "formaction" : tag.setFormaction(value); break;
			case "headers" : tag.setHeaders(value); break;
			case "height" : tag.setHeight(value); break;
			case "high" : tag.setHigh(value); break;
			case "href" : tag.setHref(value); break;
			case "hreflang" : tag.setHreflang(value); break;
			case "httpEquiv" : tag.setHttpEquiv(value); break;
			case "ismap" : tag.setIsmap(value); break;
			case "keytype" : tag.setKeytype(value); break;
			case "kind" : tag.setKind(value); break;
			case "label" : tag.setLabel(value); break;
			case "list" : tag.setList(value); break;
			case "loop" : tag.setLoop(value); break;
			case "low" : tag.setLow(value); break;
			case "manifest" : tag.setManifest(value); break;
			case "max" : tag.setMax(value); break;
			case "maxlength" : tag.setMaxlength(value); break;
			case "media" : tag.setMedia(value); break;
			case "method" : tag.setMethod(value); break;
			case "min" : tag.setMin(value); break;
			case "multiple" : tag.setMultiple(value); break;
			case "muted" : tag.setMuted(value); break;
			case "name" : tag.setName(value); break;
			case "novalidate" : tag.setNovalidate(value); break;
			case "open" : tag.setOpen(value); break;
			case "optimum" : tag.setOptimum(value); break;
			case "pattern" : tag.setPattern(value); break;
			case "placeholder" : tag.setPlaceholder(value); break;
			case "poster" : tag.setPoster(value); break;
			case "preload" : tag.setPreload(value); break;
			case "readonly" : tag.setReadonly(value); break;
			case "rel" : tag.setRel(value); break;
			case "required" : tag.setRequired(value); break;
			case "reversed" : tag.setReversed(value); break;
			case "rows" : tag.setRows(value); break;
			case "rowspan" : tag.setRowspan(value); break;
			case "sandbox" : tag.setSandbox(value); break;
			case "scope" : tag.setScope(value); break;
			case "scoped" : tag.setScoped(value); break;
			case "selected" : tag.setSelected(value); break;
			case "shape" : tag.setShape(value); break;
			case "size" : tag.setSize(value); break;
			case "sizes" : tag.setSizes(value); break;
			case "span" : tag.setSpan(value); break;
			case "src" : tag.setSrc(value); break;
			case "srcdoc" : tag.setSrcdoc(value); break;
			case "srclang" : tag.setSrclang(value); break;
			case "srcset" : tag.setSrcset(value); break;
			case "start" : tag.setStart(value); break;
			case "step" : tag.setStep(value); break;
			case "target" : tag.setTarget(value); break;
			case "type" : tag.setType(value); break;
			case "usemap" : tag.setUsemap(value); break;
			case "value" : tag.setValue(value); break;
			case "width" : tag.setWidth(value); break;
			case "wrap" : tag.setWrap(value); break;
			case "accesskey" : tag.setAccesskey(value); break;
			case "contenteditable" : tag.setContenteditable(value); break;
			case "contextmenu" : tag.setContextmenu(value); break;
			case "dir" : tag.setDir(value); break;
			case "data" : tag.setData(value); break;
			case "draggable" : tag.setDraggable(value); break;
			case "dropzone" : tag.setDropzone(value); break;
			case "hidden" : tag.setHidden(value); break;
			case "lang" : tag.setLang(value); break;
			case "spellcheck" : tag.setSpellcheck(value); break;
			case "style" : tag.setStyle(value); break;
			case "tabindex" : tag.setTabindex(value); break;
			case "title" : tag.setTitle(value); break;
			case "translate" : tag.setTranslate(value); break;
			case "onabort" : tag.setOnabort(value); break;
			case "onafterprint" : tag.setOnafterprint(value); break;
			case "onbeforeprint" : tag.setOnbeforeprint(value); break;
			case "onbeforeunload" : tag.setOnbeforeunload(value); break;
			case "onblur" : tag.setOnblur(value); break;
			case "oncanplay" : tag.setOncanplay(value); break;
			case "oncanplaythrough" : tag.setOncanplaythrough(value); break;
			case "onchange" : tag.setOnchange(value); break;
			case "onclick" : tag.setOnclick(value); break;
			case "oncontextmenu" : tag.setOncontextmenu(value); break;
			case "oncopy" : tag.setOncopy(value); break;
			case "oncuechange" : tag.setOncuechange(value); break;
			case "oncut" : tag.setOncut(value); break;
			case "ondblclick" : tag.setOndblclick(value); break;
			case "ondrag" : tag.setOndrag(value); break;
			case "ondragend" : tag.setOndragend(value); break;
			case "ondragenter" : tag.setOndragenter(value); break;
			case "ondragleave" : tag.setOndragleave(value); break;
			case "ondragover" : tag.setOndragover(value); break;
			case "ondragstart" : tag.setOndragstart(value); break;
			case "ondurationchanged" : tag.setOndurationchanged(value); break;
			case "onemptied" : tag.setOnemptied(value); break;
			case "onended" : tag.setOnended(value); break;
			case "onerror" : tag.setOnerror(value); break;
			case "onfocus" : tag.setOnfocus(value); break;
			case "onhashchange" : tag.setOnhashchange(value); break;
			case "oninput" : tag.setOninput(value); break;
			case "oninvalid" : tag.setOninvalid(value); break;
			case "onkeydown" : tag.setOnkeydown(value); break;
			case "onkeypress" : tag.setOnkeypress(value); break;
			case "onkeyup" : tag.setOnkeyup(value); break;
			case "onload" : tag.setOnload(value); break;
			case "onloaddeddata" : tag.setOnloaddeddata(value); break;
			case "onloadedmetadata" : tag.setOnloadedmetadata(value); break;
			case "onloadstart" : tag.setOnloadstart(value); break;
			case "onmousedown" : tag.setOnmousedown(value); break;
			case "onmousemove" : tag.setOnmousemove(value); break;
			case "onmouseout" : tag.setOnmouseout(value); break;
			case "onmouseover" : tag.setOnmouseover(value); break;
			case "onmouseup" : tag.setOnmouseup(value); break;
			case "onmousewheel" : tag.setOnmousewheel(value); break;
			case "onoffline" : tag.setOnoffline(value); break;
			case "ononline" : tag.setOnonline(value); break;
			case "onpagehide" : tag.setOnpagehide(value); break;
			case "onpageshow" : tag.setOnpageshow(value); break;
			case "onpaste" : tag.setOnpaste(value); break;
			case "onpuase" : tag.setOnpuase(value); break;
			case "onplay" : tag.setOnplay(value); break;
			case "onplaying" : tag.setOnplaying(value); break;
			case "onpopstate" : tag.setOnpopstate(value); break;
			case "onprogress" : tag.setOnprogress(value); break;
			case "onratechange" : tag.setOnratechange(value); break;
			case "onreset" : tag.setOnreset(value); break;
			case "onresize" : tag.setOnresize(value); break;
			case "onscroll" : tag.setOnscroll(value); break;
			case "onsearch" : tag.setOnsearch(value); break;
			case "onseeked" : tag.setOnseeked(value); break;
			case "onseeking" : tag.setOnseeking(value); break;
			case "onselect" : tag.setOnselect(value); break;
			case "onshow" : tag.setOnshow(value); break;
			case "onstalled" : tag.setOnstalled(value); break;
			case "onstorage" : tag.setOnstorage(value); break;
			case "onsubmit" : tag.setOnsubmit(value); break;
			case "onsuspend" : tag.setOnsuspend(value); break;
			case "ontimeupdate" : tag.setOntimeupdate(value); break;
			case "ontoggle" : tag.setOntoggle(value); break;
			case "onunload" : tag.setOnunload(value); break;
			case "onvolumechange" : tag.setOnvolumechange(value); break;
			case "onwaiting" : tag.setOnwaiting(value); break;
			case "onwheel" : tag.setOnwheel(value); break;
			case "class" : tag.setClasses(value); break;
			case "id" : tag.setId(value); break;
		}	
	}

	public static int checkSet(Tag tag, String attr, String value){
		setMethod(tag,attr,value);
		String output = getMethod(tag,attr);
		if(output == null) return 1;
		else return 0;
	}
}